[workspace]
members = ["aubio_test", "band_audio_input", "band_frame_extractor"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Virgile HENRY"]

[workspace.dependencies]
# Own crates
band_audio_input = { path = "./band_audio_input" }
band_frame_extractor = { path = "./band_frame_extractor" }

# Dependencies
rubato = "5.0.0"
tracing = "0.1.44"
