[workspace]
members = [
    "band_audio_input",
    "band_frame_extractor",
    "band_tools"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Virgile HENRY"]

[workspace.dependencies]
# Own crates
band_audio_input = { path = "./band_audio_input" }
band_frame_extractor = { path = "./band_frame_extractor" }
band_tools = { path = "./band_tools" }

# Dependencies
cpal = "0.18.2"
realfft = "3.5.0"
ringbuf = "0.5.1"
rubato = "5.0.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
